name: Check diff size
on:
  pull_request:
    # The restrictions on the types of pull_request event that can trigger this
    # workflow is intentional. We only want to run the check for the diff size
    # when the PR is new or reopened PR, or when new changes come in.
    types: [opened, reopened, synchronized]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Labels
        uses: danger/danger-js@9.1.8
        with:
          args: "--dangerfile Automattic/peril-settings/org/pr/diff-size.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
