name: Run Checks with Danger
# As a test, since I'm not getting any workflow triggered, let's change the
# events to something simple
on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node_version: 10.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules

      - name: Yarn Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        # frozen-lockfile will make the build fail if the lockfile is not there
        run: yarn install --frozen-lockfile

      - name: Validate Labels
        run: |
          yarn run danger ci \
            --dangerfile Automattic/peril-settings/org/pr/label.ts \
            --id pr_labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Consistency Checks
        run: |
          yarn run danger ci \
            --dangerfile Automattic/peril-settings/org/pr/ios-macos.ts \
            --id consistency_checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
